"""empty message

Revision ID: fae3da6b007d
Revises: 1850ff4bf7a0
Create Date: 2025-01-30 15:47:11.901431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae3da6b007d'
down_revision = '1850ff4bf7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=30), nullable=False))
        batch_op.create_unique_constraint(None, ['password'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
